/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Employee;

import Controller.Manager.Export.ExportScheduleController;

import javax.swing.*;

/**
 *
 * @author HieuHoang
 */
public class EmployeeHomePagePanel extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeHomePagePanel
     */
    public EmployeeHomePagePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        ManagerNameLable = new javax.swing.JLabel();
        ManagerProfileButton = new javax.swing.JButton();
        ExportScheduleButton = new javax.swing.JButton();
        ExportSalaryButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        ShowThisMonthSalary = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1280, 960));

        ManagerNameLable.setFont(new java.awt.Font("Times New Roman", 0, 40)); // NOI18N
        ManagerNameLable.setText("Hello,");

        ManagerProfileButton.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        ManagerProfileButton.setText("Profile");
        ManagerProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagerProfileButtonActionPerformed(evt);
            }
        });

        ExportScheduleButton.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        ExportScheduleButton.setText("Export This Month Schedule");
        ExportScheduleButton.setPreferredSize(new java.awt.Dimension(300, 80));
        ExportScheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportScheduleButtonActionPerformed(evt);
            }
        });

        ExportSalaryButton.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        ExportSalaryButton.setText("Export Salary");
        ExportSalaryButton.setPreferredSize(new java.awt.Dimension(300, 80));
        ExportSalaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportSalaryButtonActionPerformed(evt);
            }
        });

        ExitButton.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        ShowThisMonthSalary.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        ShowThisMonthSalary.setText("Show this month salary");
        ShowThisMonthSalary.setPreferredSize(new java.awt.Dimension(300, 80));
        ShowThisMonthSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowThisMonthSalaryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(ManagerNameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ManagerProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ExitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(ExportSalaryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(373, 373, 373))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(ExportScheduleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                                .addComponent(ShowThisMonthSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ManagerNameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ManagerProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(193, 193, 193)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ExportScheduleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ShowThisMonthSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(106, 106, 106)
                                .addComponent(ExportSalaryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>

    private void ManagerProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void ExportScheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {
        ExportScheduleController exportScheduleController = new ExportScheduleController();
        exportScheduleController.exportSchedule();

        JOptionPane.showMessageDialog(this, "Successfully exported");
    }

    private void ExportSalaryButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if (JOptionPane.showConfirmDialog(this, "Are you sure want to exit?", "WARNING",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    private void ShowThisMonthSalaryActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }


    // Variables declaration - do not modify
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton ExportSalaryButton;
    private javax.swing.JButton ExportScheduleButton;
    private javax.swing.JLabel ManagerNameLable;
    private javax.swing.JButton ManagerProfileButton;
    private javax.swing.JButton ShowThisMonthSalary;
    // End of variables declaration
}
