/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Profile;

import Controller.Profile.UpdatePasswordController;

/**
 *
 * @author HieuHoang
 */
public class ChangePasswordPanel extends javax.swing.JPanel {
    private int employeeId;
    /**
     * Creates new form AddEmployeePanel
     */
    public ChangePasswordPanel(int employeeId) {
        this.employeeId = employeeId;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        phoneNumber = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        inputOldPassword = new javax.swing.JPasswordField();
        inputNewPassword = new javax.swing.JPasswordField();
        inputConfirmPassword = new javax.swing.JPasswordField();

        jLabel1.setText("jLabel1");

        setPreferredSize(new java.awt.Dimension(500, 250));

        name.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        name.setText("Old password:");
        name.setPreferredSize(new java.awt.Dimension(90, 40));

        phoneNumber.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        phoneNumber.setText("New password:");
        phoneNumber.setPreferredSize(new java.awt.Dimension(90, 40));

        address.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        address.setText("Confirm new password:");
        address.setPreferredSize(new java.awt.Dimension(90, 40));

        inputOldPassword.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        inputNewPassword.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        inputConfirmPassword.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(inputConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(inputNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(inputOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(8, 8, 8))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(inputOldPassword)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(inputNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(inputConfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                                .addGap(1, 1, 1))
                                        .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(137, 137, 137))
        );
    }// </editor-fold>
    private boolean validateOldPassword(){
        UpdatePasswordController updatePasswordController = new UpdatePasswordController(employeeId, new String(inputOldPassword.getPassword())
                                                            ,new String(inputNewPassword.getPassword()));
        return updatePasswordController.checkOldPassword();
    }

    private boolean validateNewPassword(){
        return new String(inputNewPassword.getPassword()).equals(new String(inputConfirmPassword.getPassword()));
    }

    public String updatePassword(){
        if (validateOldPassword() && validateNewPassword())
            return new String(inputNewPassword.getPassword());
        else
            return null;
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel address;
    private javax.swing.JPasswordField inputConfirmPassword;
    private javax.swing.JPasswordField inputOldPassword;
    private javax.swing.JPasswordField inputNewPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel phoneNumber;
    // End of variables declaration
}
