/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Profile;

import Controller.Profile.GetProfileController;
import Controller.Profile.UpdatePasswordController;
import Controller.Profile.UpdateProfileController;

import javax.swing.*;

/**
 *
 * @author HieuHoang
 */
public class ProfilePanel extends javax.swing.JPanel {
    private int employeeId;
    private JFrame frame;
    private JPanel panel;
    /**
     * Creates new form AddEmployeePanel
     */
    public ProfilePanel(int employeeId, JFrame frame, JPanel panel) {
        this.panel = panel;
        this.frame = frame;
        this.employeeId = employeeId;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        name = new javax.swing.JLabel();
        phoneNumber = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        editProfileButton = new javax.swing.JButton();
        changePasswordButton = new javax.swing.JButton();
        employeeName = new javax.swing.JLabel();
        employeePhoneNumber = new javax.swing.JLabel();
        employeeAddress = new javax.swing.JLabel();
        employeeDob = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(500, 300));

        name.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        name.setText("Name:");
        name.setPreferredSize(new java.awt.Dimension(90, 40));

        phoneNumber.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        phoneNumber.setText("Phone number:");
        phoneNumber.setPreferredSize(new java.awt.Dimension(90, 40));

        address.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        address.setText("Address:");
        address.setPreferredSize(new java.awt.Dimension(90, 40));

        dob.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        dob.setText("Date of birth:");
        dob.setPreferredSize(new java.awt.Dimension(90, 40));

        editProfileButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        editProfileButton.setText("Edit Profile");
        editProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfileButtonActionPerformed(evt);
            }
        });

        changePasswordButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        changePasswordButton.setText("Change Password");
        changePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordButtonActionPerformed(evt);
            }
        });

        GetProfileController getProfileController = new GetProfileController(employeeId);
        String[] employeeId = getProfileController.getEmployeeInfo();

        employeeName.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        employeeName.setText(employeeId[0]);

        employeePhoneNumber.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        employeePhoneNumber.setText(employeeId[1]);

        employeeAddress.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        employeeAddress.setText(employeeId[2]);

        employeeDob.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        employeeDob.setText(employeeId[3]);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(editProfileButton)
                                                .addGap(30, 30, 30)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 4, Short.MAX_VALUE)
                                                .addComponent(changePasswordButton)
                                                .addGap(33, 33, 33))
                                        .addComponent(employeePhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(employeeName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(employeeAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(employeeDob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(employeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(employeePhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(employeeAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(employeeDob, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(editProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(changePasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30))
        );
    }// </editor-fold>

    private void editProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {
        EditProfilePanel editProfilePanel = new EditProfilePanel();
        int option = JOptionPane.showConfirmDialog(panel, editProfilePanel, "Confirm change?", JOptionPane.YES_NO_OPTION);
        if(option == JOptionPane.YES_OPTION){
            String[] updateProfile = editProfilePanel.updateProfile();
            UpdateProfileController updateProfileController = new UpdateProfileController(employeeId, updateProfile);
            updateProfileController.updateProfile();

            JOptionPane.showMessageDialog(this, "Successfully edited!");
        }
    }

    private void changePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {
        ChangePasswordPanel changePasswordPanel = new ChangePasswordPanel(employeeId);
        int option = JOptionPane.showConfirmDialog(panel, changePasswordPanel, "Confirm change?", JOptionPane.YES_NO_OPTION);
        if(option == JOptionPane.YES_OPTION){
            String updatePassword = changePasswordPanel.updatePassword();
            if (updatePassword == null){
                JOptionPane.showMessageDialog(this, "Wrong password input");
            }else {
                UpdatePasswordController updatePasswordController = new UpdatePasswordController(employeeId, updatePassword);
                updatePasswordController.updatePassword();

                JOptionPane.showMessageDialog(this, "Successfully updated!");
            }
        }
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel address;
    private javax.swing.JButton changePasswordButton;
    private javax.swing.JLabel dob;
    private javax.swing.JButton editProfileButton;
    private javax.swing.JLabel employeeAddress;
    private javax.swing.JLabel employeeDob;
    private javax.swing.JLabel employeeName;
    private javax.swing.JLabel employeePhoneNumber;
    private javax.swing.JLabel name;
    private javax.swing.JLabel phoneNumber;
    // End of variables declaration
}
